### ISSUE TITLE
Relative vs. Absolute Path

### ISSUE THREAD

**Issue by optikfluffel** [mvc-works/gulp-rev-manifest-replace#2]
Hi :)

In your [README](https://github.com/mvc-works/gulp-rev-manifest-replace#options) you say

> Since `rev-manifest.json` provides absolute paths, I have to figure out the relative ones.

but the `manifest.json` files I get here all have relative paths and look more like this:

``` json
{
  "devices.png": "devices-936448b0.png"
}
```

works anyhow for now, but I wondered if your README is outdated or so.

Thanks

**Comment by tiye** [comment]
@optikfluffel This plugin is not used for long. Please use [gulp-rev-all](https://github.com/smysnk/gulp-rev-all) or [Webpack](https://github.com/petehunt/webpack-howto)(I'd prefer Webpack) instead.

I'll update the README saying it's outdated soon.
